import type { Metadata } from 'next';
import { setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import EnContent, { frontmatter as enFrontmatter } from './en.mdx';
import ZhContent, { frontmatter as zhFrontmatter } from './zh.mdx';
import DeContent, { frontmatter as deFrontmatter } from './de.mdx';
import { DocsTrustFooter } from '@/components/docs/DocsTrustFooter';

/**
 * Per-route wrapper — auto-generated by
 * scripts/docs-migration/generate-page-wrappers.mjs.
 *
 * Picks the locale-specific MDX at render time. If a translation is
 * missing the EN fallback is served (zh.mdx / de.mdx for API pages
 * are EN copies until translations land — see migrate.mjs §applyFallback).
 *
 * Path: src/app/[locale]/docs/guides/credit-pilot
 */
const SITE_URL = 'https://aster-lang.cloud';
const ROUTE_SLUG = '/docs/guides/credit-pilot';

type Props = {
  params: Promise<{ locale: string }>;
};

type Frontmatter = {
  title?: string;
  description?: string;
  /** True when this locale's MDX is an EN copy pending translation. */
  fallback?: boolean;
};

const FRONTMATTER: Record<string, Frontmatter> = {
  en: enFrontmatter ?? {},
  zh: zhFrontmatter ?? {},
  de: deFrontmatter ?? {},
};

function localizedDocsUrl(locale: string): string {
  const prefix = locale === 'en' ? '' : `/${locale}`;
  return `${SITE_URL}${prefix}${ROUTE_SLUG}`;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const fm = FRONTMATTER[locale] ?? FRONTMATTER.en;

  // SEO policy for fallback variants (zh/de pages whose content is an EN
  // copy): canonicalize to the EN source and noindex so search engines
  // don't index duplicate English content under localized URLs. The
  // `fallback: true` flag is maintained by
  // scripts/docs-migration/mark-fallbacks.mjs.
  const isFallback = fm.fallback === true;
  const canonical = isFallback
    ? localizedDocsUrl('en')
    : localizedDocsUrl(locale);

  return {
    title: fm.title ? `${fm.title} · Aster Cloud Docs` : 'Aster Cloud Docs',
    description: fm.description,
    ...(isFallback && { robots: { index: false, follow: true } }),
    alternates: {
      canonical,
      languages: {
        en: localizedDocsUrl('en'),
        zh: localizedDocsUrl('zh'),
        de: localizedDocsUrl('de'),
        'x-default': localizedDocsUrl('en'),
      },
    },
  };
}

export default async function Page({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);
  const fm = FRONTMATTER[locale] ?? FRONTMATTER.en;
  // Phase 4 — every docs page renders a trust footer (last updated /
  // API version / changelog link / suggest edit). The footer reads
  // MDX frontmatter so adding fields is a no-build-config change in
  // the .mdx file itself.
  const footer = (
    <DocsTrustFooter frontmatter={fm} routeSlug={ROUTE_SLUG} locale={locale} />
  );
  if (locale === 'zh') return <><ZhContent />{footer}</>;
  if (locale === 'de') return <><DeContent />{footer}</>;
  if (locale === 'en') return <><EnContent />{footer}</>;
  notFound();
}
